# Generated by Django 4.2.25 on 2025-10-20 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('function_path', models.CharField(max_length=200, verbose_name='Function Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Task Definition',
                'verbose_name_plural': 'Task Definitions',
                'ordering': ['name'],
                'unique_together': {('name', 'function_path')},
            },
        ),
        migrations.CreateModel(
            name='TaskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50, verbose_name='Parameter Name')),
                ('parameter_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'DateTime'), ('file', 'File'), ('json', 'JSON')], max_length=20, verbose_name='Parameter Type')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='Default Value')),
                ('description', models.TextField(blank=True, verbose_name='Parameter Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskparameter_set', to='tasks.taskdefinition', verbose_name='Task Definition')),
            ],
            options={
                'verbose_name': 'Task Parameter',
                'verbose_name_plural': 'Task Parameters',
                'ordering': ['task_definition', 'parameter_name'],
                'unique_together': {('task_definition', 'parameter_name')},
            },
        ),
    ]
