# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskdefinition',
            index=models.Index(fields=['is_active'], name='tasks_taskd_is_acti_8c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdefinition',
            index=models.Index(fields=['name'], name='tasks_taskd_name_7c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskparameter',
            index=models.Index(fields=['task_definition', 'is_active'], name='tasks_taskp_task_d_9c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskparameter',
            index=models.Index(fields=['parameter_name'], name='tasks_taskp_paramet_8c9b3a_idx'),
        ),
    ]
