# Generated by Django 4.2.25 on 2025-10-21 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\*|([0-5]?\\d)) (\\*|([01]?\\d|2[0-3])) (\\*|([012]?\\d|3[01])) (\\*|([0]?\\d|1[012])) (\\*|([0-6]))$')])),
                ('parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('max_executions', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('max_failures', models.PositiveIntegerField(default=3)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('celery_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_job', to='django_celery_beat.periodictask')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='tasks.taskdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('memory_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_time', models.DurationField(blank=True, null=True)),
                ('scheduled_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='scheduler.scheduledjob')),
            ],
        ),
    ]
