# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['user', 'is_active'], name='scheduler_s_user_id_4a8b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['is_active', 'status'], name='scheduler_s_is_acti_8c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['created_at'], name='scheduler_s_created_9b8c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['last_run'], name='scheduler_s_last_ru_7c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['next_run'], name='scheduler_s_next_ru_8c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjob',
            index=models.Index(fields=['task_definition', 'is_active'], name='scheduler_s_task_d_9c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecutionlog',
            index=models.Index(fields=['scheduled_job', 'status'], name='scheduler_j_schedul_9c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecutionlog',
            index=models.Index(fields=['execution_time'], name='scheduler_j_executi_8c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecutionlog',
            index=models.Index(fields=['status', 'execution_time'], name='scheduler_j_status_7c9b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobexecutionlog',
            index=models.Index(fields=['scheduled_job', 'execution_time'], name='scheduler_j_schedul_6c9b3a_idx'),
        ),
    ]
